#!/usr/bin/env python

import sys, ConfigParser, os, argparse
from subprocess import check_output, check_call, CalledProcessError, STDOUT
from os import listdir, path, chdir
from re import search, IGNORECASE
from collections import defaultdict

def repos(hidden):
    return [x for x in listdir(".") if path.exists("%s/.git" % x) and x not in hidden]

def base_args(repo):
    return ["git", "--git-dir=%s/.git" % repo, "--work-tree=%s" % repo]

def status(repos):
    for repo in repos:
        print '\033[93m', repo, '\033[0m'
        output = check_output(base_args(repo) + ["status"])
        for line in output.split('\n'):
            match = search("# On branch (.*)", line)
            if match:
                print "# On branch \033[31m%s\033[0m" % match.group(1)
            else:
                print line

def fetch(repos):
    for repo in repos:
        print "Fetching from %s" % repo
        check_call(base_args(repo) + ["fetch"])

def checkout(repos, branch):
    for repo in repos:
        print "Checking out %s in %s" % (branch, repo)
        try:
            check_output(base_args(repo) + ["checkout", branch], stderr=STDOUT)
        except CalledProcessError, e:
            print "Failed to checkout %s\n\033[31m%s\033[0m" % (branch, e.output.strip())

def pull(repos):
    for repo in repos:
        print "Pulling from %s" % repo
        try:
            chdir(repo)
            check_call(["git", "pull"])
        finally:
            chdir("..")

def list_branches(repos, key=None):
    branches_per_repo = {}
    for repo in repos:
        branches = []
        output = check_output(base_args(repo) + ["branch", "-a"])
        for line in output.split('\n'):
            if line.strip():
                branches.append(line.strip().replace("* ", ""))
        branches_per_repo[repo] = branches
    if not key:
        all_branches = set()
        for k, v in branches_per_repo.items():
            all_branches = all_branches | set(v)
        print "\n".join(all_branches)
    else:
        result = defaultdict(list)
        for repo, branches in branches_per_repo.items():
            for branch in branches:
                if search(".*" + key + ".*", branch, flags=IGNORECASE):
                    result[repo].append(branch)
        for k, v in result.items():
            print "%s: %s" % (k, ",".join(v))

def read_hidden_repos():
    config_file = os.environ["HOME"] + "/.repos/config"
    if not os.path.exists(config_file):
        return []

    config = ConfigParser.ConfigParser()
    if len(config.read(config_file)) != 1:
        print "Could not read configuration: " + config_file
        exit(1)
    return [repo.strip() for repo in config.get("main", "hidden").split(",")]

class StatusAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        status(repo_list)

class FetchAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        fetch(repo_list)

class PullAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        pull(repo_list)

class CheckoutAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        checkout(repo_list, values)

class BranchesAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        if values:
            list_branches(repo_list, values)
        else:
            list_branches(repo_list)

if __name__ == '__main__':
    repo_list = repos(read_hidden_repos())
    if "repos" in sys.argv[0]:
        parser = argparse.ArgumentParser(description="Perform Git commands on multiple repositories")
        parser.add_argument("-s", "--status", action=StatusAction, nargs=0)
        parser.add_argument("-f", "--fetch", action=FetchAction, nargs=0)
        parser.add_argument("-p", "--pull", action=PullAction, nargs=0)
        parser.add_argument("-c", "--checkout", action=CheckoutAction, metavar="branch")
        parser.add_argument("-b", "--branches", action=BranchesAction, nargs="?", metavar="pattern")
        parser.parse_args()
    else:
        if "status" in sys.argv[0]:
            status(repo_list)
        elif "fetch" in sys.argv[0]:
            fetch(repo_list)
        elif "checkout" in sys.argv[0]:
            if len(sys.argv) != 2:
                print "usage: checkout <branch>"
                exit(1)
            checkout(repo_list, sys.argv[1])
        elif "pull" in sys.argv[0]:
            pull(repo_list)
        elif "branches" in sys.argv[0]:
            if len(sys.argv) > 1:
                list_branches(repo_list, sys.argv[1])
            else:
                list_branches(repo_list)
